<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-07-23">
<meta name="description" content="A comunicação do Copom decomposta por três LLMs em diagnóstico retrospectivo, orientação prospectiva e balanço de riscos, com validação cega por agentes independentes. O balanço de riscos antecipa a ΔSelic da reunião seguinte (+0,146 p.p. por desvio-padrão), mas o efeito é integralmente absorvido pela expectativa do Questionário Pré-Copom (+13,3 pb), sem prever a surpresa monetária. Linguagem como sinalização compartilhada, não choque autônomo.">

<title>Regra de Taylor com Sentimento do Copom — o balanço de riscos antecipa a Selic ou apenas reflete expectativas? – Portfólio do VW</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/profile.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-e3adbaa939bcd423dddc8c8a834270b4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-1a0ec396d50e794b56c0b09b01a12471.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-e3adbaa939bcd423dddc8c8a834270b4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Regra de Taylor com Sentimento do Copom — o balanço de riscos antecipa a Selic ou apenas reflete expectativas? – Portfólio do VW">
<meta property="og:description" content="A comunicação do Copom decomposta por três LLMs em diagnóstico retrospectivo, orientação prospectiva e balanço de riscos, com validação cega por agentes independentes. O balanço de riscos antecipa a ΔSelic da reunião seguinte (+0,146 p.p. por desvio-padrão), mas o efeito é integralmente absorvido pela expectativa do Questionário Pré-Copom (+13,3 pb), sem prever a surpresa monetária. Linguagem como sinalização compartilhada, não choque autônomo.">
<meta property="og:image" content="https://vitorwilher.github.io/projetos/taylor-sentimento-capa.png">
<meta property="og:site_name" content="Portfólio do VW">
<meta property="og:image:height" content="919">
<meta property="og:image:width" content="1800">
<meta name="twitter:title" content="Regra de Taylor com Sentimento do Copom — o balanço de riscos antecipa a Selic ou apenas reflete expectativas? – Portfólio do VW">
<meta name="twitter:description" content="A comunicação do Copom decomposta por três LLMs em diagnóstico retrospectivo, orientação prospectiva e balanço de riscos, com validação cega por agentes independentes. O balanço de riscos antecipa a ΔSelic da reunião seguinte (+0,146 p.p. por desvio-padrão), mas o efeito é integralmente absorvido pela expectativa do Questionário Pré-Copom (+13,3 pb), sem prever a surpresa monetária. Linguagem como sinalização compartilhada, não choque autônomo.">
<meta name="twitter:image" content="https://vitorwilher.github.io/projetos/taylor-sentimento-capa.png">
<meta name="twitter:image-height" content="919">
<meta name="twitter:image-width" content="1800">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Portfólio do VW</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cv.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projetos/index.html"> 
<span class="menu-text">Projetos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../teaching/index.html"> 
<span class="menu-text">Cursos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../research/index.html"> 
<span class="menu-text">Pesquisas</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://vitorwilher.github.io/pos-puc-rio-ia/" target="_blank"> 
<span class="menu-text">Pós em Dados e IA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://vitorwilher.github.io/anthropic-academy-cursos/" target="_blank"> 
<span class="menu-text">Anthropic</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://vitorwilher.github.io/doutorado-epge/" target="_blank"> 
<span class="menu-text">Doutorado</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../newsletter/index.html"> 
<span class="menu-text">Newsletter</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/vitorwilher"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/vitorwilher"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#visão-geral" id="toc-visão-geral" class="nav-link active" data-scroll-target="#visão-geral">Visão Geral</a></li>
  <li><a href="#motivação" id="toc-motivação" class="nav-link" data-scroll-target="#motivação">Motivação</a></li>
  <li><a href="#a-auditoria-que-reorientou-o-projeto" id="toc-a-auditoria-que-reorientou-o-projeto" class="nav-link" data-scroll-target="#a-auditoria-que-reorientou-o-projeto">A auditoria que reorientou o projeto</a></li>
  <li><a href="#metodologia-crisp-dm" id="toc-metodologia-crisp-dm" class="nav-link" data-scroll-target="#metodologia-crisp-dm">Metodologia — CRISP-DM</a></li>
  <li><a href="#arquitetura" id="toc-arquitetura" class="nav-link" data-scroll-target="#arquitetura">Arquitetura</a></li>
  <li><a href="#especificações" id="toc-especificações" class="nav-link" data-scroll-target="#especificações">1. Especificações</a></li>
  <li><a href="#resultados" id="toc-resultados" class="nav-link" data-scroll-target="#resultados">2. Resultados</a></li>
  <li><a href="#discussão" id="toc-discussão" class="nav-link" data-scroll-target="#discussão">3. Discussão</a></li>
  <li><a href="#limitações" id="toc-limitações" class="nav-link" data-scroll-target="#limitações">Limitações</a></li>
  <li><a href="#estrutura-do-projeto" id="toc-estrutura-do-projeto" class="nav-link" data-scroll-target="#estrutura-do-projeto">Estrutura do Projeto</a></li>
  <li><a href="#tecnologias" id="toc-tecnologias" class="nav-link" data-scroll-target="#tecnologias">Tecnologias</a></li>
  <li><a href="#como-executar-localmente" id="toc-como-executar-localmente" class="nav-link" data-scroll-target="#como-executar-localmente">Como Executar Localmente</a></li>
  <li><a href="#próximos-passos" id="toc-próximos-passos" class="nav-link" data-scroll-target="#próximos-passos">Próximos Passos</a></li>
  <li><a href="#referências" id="toc-referências" class="nav-link" data-scroll-target="#referências">Referências</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regra de Taylor com Sentimento do Copom — o balanço de riscos antecipa a Selic ou apenas reflete expectativas?</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Python</div>
    <div class="quarto-category">Quarto</div>
    <div class="quarto-category">LLM</div>
    <div class="quarto-category">statsmodels</div>
    <div class="quarto-category">OLS</div>
    <div class="quarto-category">GMM</div>
    <div class="quarto-category">VAR</div>
    <div class="quarto-category">Filtro de Kalman</div>
    <div class="quarto-category">Regra de Taylor</div>
    <div class="quarto-category">Política Monetária</div>
    <div class="quarto-category">Banco Central</div>
    <div class="quarto-category">Macroeconomia</div>
    <div class="quarto-category">Séries Temporais</div>
    <div class="quarto-category">python-bcb</div>
  </div>
  </div>

<div>
  <div class="description">
    A comunicação do Copom decomposta por três LLMs em diagnóstico retrospectivo, orientação prospectiva e balanço de riscos, com validação cega por agentes independentes. O balanço de riscos antecipa a ΔSelic da reunião seguinte (+0,146 p.p. por desvio-padrão), mas o efeito é integralmente absorvido pela expectativa do Questionário Pré-Copom (+13,3 pb), sem prever a surpresa monetária. Linguagem como sinalização compartilhada, não choque autônomo.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 23, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taylor-sentimento-capa.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Índice de tom hawkish-dovish (ensemble de três LLMs) sobreposto à decisão da Selic por reunião do Copom</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>🔗 Projeto-mãe: Sentimento COPOM
</div>
</div>
<div class="callout-body-container callout-body">
<p>Este trabalho é uma <strong>extensão direta</strong> do <a href="sentimento-copom.html"><strong>Sentimento COPOM</strong></a>. Lá, construímos um Índice de Tom <em>hawkish-dovish</em> das atas do Copom com <strong>três LLMs em paralelo</strong> (Gemini Flash Lite, Claude Haiku 4.5, GPT-4.1-mini). <strong>Aqui</strong>, esse índice deixa de ser o objeto final e vira um <strong>regressor</strong> numa <strong>Regra de Taylor</strong> — e, na rodada atual, é <em>reconstruído</em>: o corpus A+B das atas passa a ser lido integralmente e o tom é decomposto em dimensões econômicas distintas.</p>
<p>Uma correção importante em relação à versão anterior desta ficha: as regressões usam os <strong><em>scores</em> brutos em <span class="math inline">\([-3, +3]\)</span></strong> (padronizados por z-score), <strong>não</strong> a série calibrada em pontos percentuais da Selic disponível no projeto de origem. Não há, portanto, vazamento mecânico da calibração OLS do projeto-mãe para a Regra de Taylor estimada aqui.</p>
</div>
</div>
<section id="visão-geral" class="level2">
<h2 class="anchored" data-anchor-id="visão-geral">Visão Geral</h2>
<p>Este projeto testa, seguindo a metodologia <strong>CRISP-DM</strong>, uma pergunta de economia monetária aplicada: <strong>o sentimento da comunicação do Copom, medido por LLMs, tem informação sobre a Selic que os fundamentos macro não capturam?</strong></p>
<blockquote class="blockquote">
<p><strong>Repositório:</strong> <a href="https://github.com/vitorwilher/taylor-sentimento">github.com/vitorwilher/taylor-sentimento</a> — base, scripts de estimação, paper e caches de API versionados.</p>
</blockquote>
<p>A resposta encontrada é mais interessante — e mais restritiva — do que a hipótese inicial sugeria. O tom <strong>explica</strong> a Selic contemporânea com folga e o <strong>balanço de riscos de inflação antecipa</strong> a decisão da reunião seguinte. Mas quando se confronta esse conteúdo antecedente com a expectativa do mercado medida <strong>antes</strong> da reunião, o efeito se revela <strong>integralmente absorvido pela expectativa</strong>: a linguagem desloca o consenso, não a surpresa.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Tese central (revisada)
</div>
</div>
<div class="callout-body-container callout-body">
<p>A hipótese original era que o tom carrega sinal <em>incremental</em> sobre a decisão. Os resultados obrigam a <strong>reposicionar a pergunta</strong>: o balanço de riscos antecipa a ΔSelic da reunião seguinte em <strong>+0,146 p.p. por desvio-padrão</strong> (<span class="math inline">\(p = 0{,}001\)</span>), mas desloca a <strong>expectativa média do Questionário Pré-Copom em +13,3 pontos-base</strong> — praticamente toda a decisão realizada (+12,9 pb). A <strong>surpresa</strong> residual é de <strong>−0,4 pb</strong>, estatisticamente indistinguível de zero. A comunicação do Copom opera como <strong>mecanismo de sinalização compartilhado com o mercado</strong>, não como choque monetário autônomo.</p>
</div>
</div>
<hr>
</section>
<section id="motivação" class="level2">
<h2 class="anchored" data-anchor-id="motivação">Motivação</h2>
<p>A Regra de Taylor <span class="citation" data-cites="taylor1993">[@taylor1993]</span> postula que o banco central ajusta a taxa de juros em resposta a dois desvios: a inflação em relação à meta e o produto em relação ao potencial. É uma das relações mais estimadas em macroeconomia — mas trata a comunicação do banco central como ruído. Ao mesmo tempo, uma literatura crescente mostra que a <em>comunicação</em> é, em si, um instrumento de política monetária <span class="citation" data-cites="blinder2008 hansen2018">[@blinder2008; @hansen2018]</span>.</p>
<p>O projeto-mãe transformou esse tom em série quantitativa. Este projeto fecha o elo, colocando as duas peças na mesma regressão — e depois submete o resultado a um teste que boa parte da literatura de <em>central bank communication</em> não faz: <strong>descontar o que o mercado já esperava</strong>.</p>
<section id="perguntas-de-pesquisa" class="level3">
<h3 class="anchored" data-anchor-id="perguntas-de-pesquisa">Perguntas de pesquisa</h3>
<ol type="1">
<li><strong>O sentimento sobrevive aos controles?</strong> Com hiato do produto e desvio de inflação na regressão, <span class="math inline">\(\hat{\delta}\)</span> permanece positivo e significante?</li>
<li><strong>O tom antecede a decisão?</strong> O sentimento da ata <span class="math inline">\(t\)</span> prevê a ΔSelic da reunião <span class="math inline">\(t+1\)</span> — ou isso é contemporaneidade disfarçada?</li>
<li><strong>Qual dimensão da linguagem carrega o sinal?</strong> Diagnóstico retrospectivo, orientação prospectiva e balanço de riscos são objetos econômicos distintos; agregá-los num único índice pode estar misturando informação com ruído.</li>
<li><strong>O sinal é antecipação ou surpresa?</strong> Se o mercado já precifica o conteúdo da ata, o efeito sobre a decisão não é informação nova.</li>
<li><strong>A conclusão depende do LLM?</strong> Sinal e significância são estáveis entre Claude, Gemini e OpenAI?</li>
</ol>
<hr>
</section>
</section>
<section id="a-auditoria-que-reorientou-o-projeto" class="level2">
<h2 class="anchored" data-anchor-id="a-auditoria-que-reorientou-o-projeto">A auditoria que reorientou o projeto</h2>
<p>A versão inicial deste trabalho estimava a Regra de Taylor com o índice agregado herdado. Uma auditoria do corpus revelou duas coisas — uma tranquilizadora e uma que exigiu refazer a escoragem:</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>O que a auditoria encontrou
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Sem vazamento (verificado).</strong> A extração já excluía corretamente a <strong>seção C</strong> das atas, que contém discussão, decisão e votação. E os <em>scores</em> usados são as saídas brutas dos modelos em <span class="math inline">\([-3, +3]\)</span> — a calibração em p.p. da Selic nunca entrou nesta base.</p>
<p><strong>Truncagem material (corrigida).</strong> A extração legada limitava as seções A+B a <strong>4.500 caracteres</strong>. O corte atingiu <strong>35 das 48 atas</strong>. Entre as atas truncadas, a extração integral recuperou <strong>mediana de 6.042 caracteres</strong> (máximo de 10.061) — cobertura temporal desigual, com risco de eliminar justamente o conteúdo prospectivo das atas mais longas.</p>
</div>
</div>
<p>A resposta foi reconstruir o corpus (<code>data/raw/atas_full_cache.json</code>, seções A+B integrais, seção C excluída) e <strong>reescorar as 48 atas</strong> em dimensões separadas, com cada justificativa vinculada a um identificador de parágrafo (<code>P01</code>, <code>P02</code>, …) para auditabilidade.</p>
<section id="o-índice-prospectivo-em-quatro-dimensões" class="level3">
<h3 class="anchored" data-anchor-id="o-índice-prospectivo-em-quatro-dimensões">O índice prospectivo em quatro dimensões</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Dimensão</th>
<th>O que mede</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>tom_retrospectivo</code></td>
<td>Leitura dos dados e condições <strong>já observadas</strong></td>
</tr>
<tr class="even">
<td><code>orientacao_prospectiva</code></td>
<td>Indicação explícita sobre a <strong>postura monetária futura</strong></td>
</tr>
<tr class="odd">
<td><code>balanco_riscos_inflacao</code></td>
<td><strong>Assimetria dos riscos</strong> para a inflação</td>
</tr>
<tr class="even">
<td><code>confianca</code></td>
<td>Grau de clareza da classificação (diagnóstico de validade)</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="metodologia-crisp-dm" class="level2">
<h2 class="anchored" data-anchor-id="metodologia-crisp-dm">Metodologia — CRISP-DM</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Fase</th>
<th>Aplicação no Projeto</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1. Entendimento do Negócio</strong></td>
<td>Regra de Taylor <em>forward-looking</em> com suavização (<span class="citation" data-cites="taylor1993">@taylor1993</span>; <span class="citation" data-cites="clarida2000">@clarida2000</span>). Hipótese testável: o tom adiciona poder explicativo além de hiato e desvio de inflação — e, na rodada revisada, se esse conteúdo é <strong>antecipação</strong> ou <strong>surpresa</strong></td>
</tr>
<tr class="even">
<td><strong>2. Entendimento dos Dados</strong></td>
<td>Cinco blocos: Selic (SGS 432); corpus integral das atas; Focus IPCA 12m suavizada; hiato (IBC-Br, SGS 24364); <strong>Questionário Pré-Copom</strong> (42 edições quantitativas, reuniões 238+). A unidade é a <strong>reunião do Copom</strong> (232–279), não o mês</td>
</tr>
<tr class="odd">
<td><strong>3. Preparação dos Dados</strong></td>
<td><code>01_build_base.py</code> monta <code>base_taylor.csv</code> (48 reuniões). <code>09_prepare_forward_texts.py</code> reconstrói o corpus A+B sem truncagem. <code>14/15_*</code> coletam o QPC e constroem a surpresa da decisão. <em>Cache</em> incremental por fonte</td>
</tr>
<tr class="even">
<td><strong>4. Modelagem</strong></td>
<td>OLS com erros <strong>HAC (Newey-West, 2 defasagens)</strong> como referência; <strong>TSLS e GMM em dois passos</strong> para endogeneidade; <strong>filtro de Kalman</strong> como hiato alternativo; <strong>VAR</strong> e <strong>VECM</strong> como exploratórios; <strong>regressões móveis</strong> para estabilidade; <strong>bootstrap (5.000 réplicas)</strong> e <strong><em>leave-one-out</em></strong> na especificação de surpresa</td>
</tr>
<tr class="odd">
<td><strong>5. Avaliação</strong></td>
<td>Significância de <span class="math inline">\(\hat{\delta}\)</span>; ganho de <span class="math inline">\(\bar{R}^2\)</span>; decomposição por dimensão textual; <strong>identidade decisão = expectativa + surpresa</strong>; robustez ao provedor de LLM e à fonte do hiato; <strong>validação cega por dois agentes independentes</strong></td>
</tr>
<tr class="even">
<td><strong>6. Implantação</strong></td>
<td><em>Paper</em> reprodutível em Quarto + LaTeX; base regenerável apagando o <em>cache</em>; CHANGELOG + <code>versions/</code></td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="arquitetura" class="level2">
<h2 class="anchored" data-anchor-id="arquitetura">Arquitetura</h2>
<div class="cell" data-layout-align="default">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>flowchart LR</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  subgraph Corpus["Corpus reconstruído"]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    ATAS[(atas_full_cache.json&lt;br&gt;seções A+B integrais&lt;br&gt;seção C excluída)]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  end</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  subgraph Coleta["Coleta via API BCB"]</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    SGS432[(SGS 432&lt;br&gt;meta Selic)]</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    FOCUS[(Focus IPCA 12m)]</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    META[(SGS 13521&lt;br&gt;meta de inflação)]</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    IBC[(SGS 24364&lt;br&gt;IBC-Br dessaz.)]</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    QPC[(Questionário Pré-Copom&lt;br&gt;42 edições)]</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  end</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  ATAS --&gt; SCORE[["Escoragem 3 LLMs&lt;br&gt;4 dimensões · evidência por parágrafo"]]</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  SCORE --&gt; VALID{{"Validação cega&lt;br&gt;2 agentes independentes"}}</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  VALID --&gt; BUILD</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  SGS432 --&gt; BUILD</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  FOCUS --&gt; BUILD</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  META --&gt; BUILD</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  IBC --&gt; BUILD</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  BUILD[["base_taylor.csv&lt;br&gt;48 reuniões"]] --&gt; EST</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  subgraph EST["Estimação"]</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    M01["M0 / M1&lt;br&gt;contemporânea"]</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    M2["M2 antecedente&lt;br&gt;por dimensão"]</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    IV["TSLS / GMM"]</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    KAL["hiato Kalman"]</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    DIN["VAR · VECM · rolling"]</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  end</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>  QPC --&gt; SURP[["Surpresa monetária&lt;br&gt;decisão − expectativa QPC"]]</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>  M2 --&gt; SURP</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>  SURP --&gt; DEC["Identidade:&lt;br&gt;decisão = expectativa + surpresa"]</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>  EST --&gt; PDF([Quarto Render PDF])</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>  DEC --&gt; PDF</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>

</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<hr>
</section>
<section id="especificações" class="level2">
<h2 class="anchored" data-anchor-id="especificações">1. Especificações</h2>
<section id="regra-de-taylor-contemporânea" class="level3">
<h3 class="anchored" data-anchor-id="regra-de-taylor-contemporânea">1.1 Regra de Taylor contemporânea</h3>
<p><span class="math display">\[
i_t = \rho\, i_{t-1} + (1-\rho)\big[\alpha + \beta\,(\pi^e_t - \pi^*_t) + \gamma\,\text{hiato}_t\big] + \delta\, S^z_t + \varepsilon_t
\]</span></p>
</section>
<section id="especificação-antecedente-dinâmica" class="level3">
<h3 class="anchored" data-anchor-id="especificação-antecedente-dinâmica">1.2 Especificação antecedente dinâmica</h3>
<p><span class="math display">\[
\Delta i_{t+1} = c + \phi\,\Delta i_t + \beta\,\text{desvio}_t + \gamma\,\text{hiato}_t + \delta\, S^z_t + \varepsilon_{t+1}
\]</span></p>
<p>O controle por <span class="math inline">\(\Delta i_t\)</span> é o teste decisivo: sem ele, a ata <em>parece</em> prever a próxima reunião apenas porque acompanha a decisão corrente.</p>
</section>
<section id="decomposição-da-surpresa" class="level3">
<h3 class="anchored" data-anchor-id="decomposição-da-surpresa">1.3 Decomposição da surpresa</h3>
<p>Com a expectativa do QPC coletada <strong>antes</strong> da reunião, vale a identidade contábil:</p>
<p><span class="math display">\[
\underbrace{\Delta i_{t+1}}_{\text{decisão realizada}} = \underbrace{E^{QPC}_t[\Delta i_{t+1}]}_{\text{expectativa}} + \underbrace{u_{t+1}}_{\text{surpresa}}
\]</span></p>
<p>Estimar a mesma regressão sobre cada componente separa <strong>sinalização</strong> (o índice move a expectativa) de <strong>choque</strong> (o índice move a surpresa).</p>
<hr>
</section>
</section>
<section id="resultados" class="level2">
<h2 class="anchored" data-anchor-id="resultados">2. Resultados</h2>
<section id="a-regra-de-taylor-contemporânea" class="level3">
<h3 class="anchored" data-anchor-id="a-regra-de-taylor-contemporânea">2.1 A Regra de Taylor contemporânea</h3>
<p>O sentimento sobrevive aos controles com folga. Comparação M0 (<em>baseline</em>) → M1 (aumentada), <span class="math inline">\(n = 47\)</span>, erros HAC:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Modelo</th>
<th><span class="math inline">\(\hat{\delta}\)</span> (sentimento)</th>
<th><span class="math inline">\(p\)</span>-valor</th>
<th><span class="math inline">\(\bar{R}^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>M0 — Baseline</strong></td>
<td>—</td>
<td>—</td>
<td>0,9932</td>
</tr>
<tr class="even">
<td><strong>M1 — Aumentada</strong></td>
<td><strong>+0,283</strong></td>
<td><span class="math inline">\(&lt; 0{,}001\)</span></td>
<td><strong>0,9960</strong></td>
</tr>
</tbody>
</table>
<p>O coeficiente do sentimento padronizado é <strong>+0,283 p.p. por desvio-padrão</strong> (EP HAC 0,056; IC 95% [0,169; 0,396]). O desvio da inflação cai de <span class="math inline">\(\hat\beta = 0{,}669\)</span> para <span class="math inline">\(0{,}415\)</span> quando o tom entra — parte do que se atribuía aos fundamentos observáveis estava, na verdade, na linguagem.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Estabilidade temporal
</div>
</div>
<div class="callout-body-container callout-body">
<p>Regressões móveis com janela de 24 reuniões: o coeficiente do sentimento é <strong>positivo em 100% das janelas</strong> e significante a 5% em <strong>95,8%</strong> delas (23 de 24). Com janelas de 28 e 32 reuniões, a proporção significativa vai a <strong>100%</strong>. Não é artefato de subperíodo.</p>
</div>
</div>
</section>
<section id="antecedência-o-controle-que-desfaz-o-resultado-bruto" class="level3">
<h3 class="anchored" data-anchor-id="antecedência-o-controle-que-desfaz-o-resultado-bruto">2.2 Antecedência: o controle que desfaz o resultado bruto</h3>
<p>Sem controlar a decisão corrente, o sentimento parece prever a próxima reunião (<span class="math inline">\(\hat\delta = +0{,}509\)</span>, <span class="math inline">\(p &lt; 0{,}001\)</span>). <strong>Com</strong> o controle, o efeito evapora:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Especificação M2</th>
<th><span class="math inline">\(\hat{\delta}\)</span></th>
<th><span class="math inline">\(p\)</span>-valor</th>
<th><span class="math inline">\(\bar{R}^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>M2a</strong> — sem controlar <span class="math inline">\(\Delta i_t\)</span></td>
<td>+0,509</td>
<td><span class="math inline">\(&lt; 0{,}001\)</span></td>
<td>0,440</td>
</tr>
<tr class="even">
<td><strong>M2b</strong> — dinâmica, com <span class="math inline">\(\Delta i_t\)</span></td>
<td><strong>+0,045</strong></td>
<td>0,407</td>
<td>0,837</td>
</tr>
</tbody>
</table>
<p>A “antecedência” do índice <strong>agregado</strong> era contemporaneidade disfarçada. TSLS e GMM em dois passos (instrumentando os quatro regressores com defasagens 1 e 2) confirmam: <span class="math inline">\(\hat\delta = -0{,}066\)</span> (<span class="math inline">\(p = 0{,}64\)</span>) e <span class="math inline">\(-0{,}104\)</span> (<span class="math inline">\(p = 0{,}47\)</span>), com o teste J de Hansen não rejeitando as sobreidentificações (<span class="math inline">\(p = 0{,}49\)</span>).</p>
</section>
<section id="a-decomposição-resolve-o-enigma" class="level3">
<h3 class="anchored" data-anchor-id="a-decomposição-resolve-o-enigma">2.3 A decomposição resolve o enigma</h3>
<p>O índice agregado falha porque <strong>mistura objetos econômicos distintos</strong>. Separando as dimensões na especificação dinâmica (dependente: ΔSelic em <span class="math inline">\(t+1\)</span>; controles: <span class="math inline">\(\Delta i_t\)</span>, desvio de inflação, hiato Kalman):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Dimensão textual</th>
<th><span class="math inline">\(\hat{\delta}\)</span></th>
<th>EP HAC</th>
<th><span class="math inline">\(p\)</span>-valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sentimento legado (agregado)</td>
<td>+0,045</td>
<td>0,053</td>
<td>0,407</td>
</tr>
<tr class="even">
<td>Tom retrospectivo</td>
<td>+0,102</td>
<td>0,065</td>
<td>0,127</td>
</tr>
<tr class="odd">
<td>Orientação prospectiva</td>
<td>−0,022</td>
<td>0,046</td>
<td>0,642</td>
</tr>
<tr class="even">
<td><strong>Balanço de riscos de inflação</strong></td>
<td><strong>+0,146</strong></td>
<td>0,042</td>
<td><strong>0,001</strong></td>
</tr>
</tbody>
</table>
<p>O conteúdo antecedente está <strong>concentrado no balanço de riscos</strong> — não na orientação prospectiva explícita, que seria o candidato intuitivo. Na especificação decomposta (as três dimensões juntas), o balanço de riscos mantém <strong>+0,129</strong> (<span class="math inline">\(p = 0{,}006\)</span>) e a orientação prospectiva vira <strong>negativa e significante</strong> (−0,101, <span class="math inline">\(p = 0{,}006\)</span>), sugerindo que as duas dimensões capturam informações parcialmente opostas.</p>
<p><strong>Robustez ao provedor:</strong> o sinal é positivo nos três LLMs, com significância individual para Claude (+0,132, <span class="math inline">\(p = 0{,}002\)</span>) e Gemini (+0,124, <span class="math inline">\(p &lt; 0{,}001\)</span>); OpenAI mantém o sinal (+0,076) mas não a significância (<span class="math inline">\(p = 0{,}148\)</span>).</p>
</section>
<section id="validação-cega-por-agentes-independentes" class="level3">
<h3 class="anchored" data-anchor-id="validação-cega-por-agentes-independentes">2.4 Validação cega por agentes independentes</h3>
<p>Antes de levar o índice a sério, dois agentes classificaram independentemente 12 atas do piloto, <strong>sem acesso aos scores dos provedores</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Comparação (balanço de riscos)</th>
<th>Spearman</th>
<th>Concordância de sinal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Agente A × Agente B</td>
<td><strong>0,954</strong></td>
<td><strong>100%</strong></td>
</tr>
<tr class="even">
<td>Consenso dos agentes × <em>ensemble</em> dos LLMs</td>
<td><strong>0,777</strong></td>
<td>75%</td>
</tr>
</tbody>
</table>
<p>Entre os três LLMs no corpus completo (48 atas), o balanço de riscos tem concordância de sinal entre <strong>91,7% e 97,9%</strong> — a dimensão mais estável das quatro.</p>
</section>
<section id="o-teste-decisivo-sinalização-ou-surpresa" class="level3">
<h3 class="anchored" data-anchor-id="o-teste-decisivo-sinalização-ou-surpresa">2.5 O teste decisivo: sinalização ou surpresa?</h3>
<p>Usando as 42 edições quantitativas do QPC, a decomposição da identidade contábil (coeficientes em pontos-base por desvio-padrão do balanço de riscos, controles macro parcimoniosos, erros HAC):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Componente</th>
<th>Coeficiente (pb)</th>
<th><span class="math inline">\(p\)</span>-valor</th>
<th><span class="math inline">\(\bar{R}^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Decisão realizada</strong></td>
<td><strong>+12,9</strong></td>
<td><span class="math inline">\(&lt; 0{,}01\)</span></td>
<td>0,885</td>
</tr>
<tr class="even">
<td><strong>Expectativa média do QPC</strong></td>
<td><strong>+13,3</strong></td>
<td><span class="math inline">\(&lt; 0{,}01\)</span></td>
<td>0,919</td>
</tr>
<tr class="odd">
<td><strong>Surpresa</strong> (resíduo)</td>
<td><strong>−0,4</strong></td>
<td>0,872</td>
<td>−0,042</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\underbrace{12{,}916}_{\text{decisão realizada}} = \underbrace{13{,}333}_{\text{expectativa QPC}} + \underbrace{(-0{,}417)}_{\text{surpresa}}
\]</span></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>O resultado central
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>O efeito é integralmente absorvido pela expectativa.</strong> O bootstrap com 5.000 réplicas coloca o efeito sobre a expectativa entre <strong>+5,7 e +20,9 pb</strong> (probabilidade de ser positivo: 99,9%), e todas as estimativas <em>leave-one-out</em> permanecem positivas. Já a surpresa tem IC bootstrap de <strong>[−5,9; +4,5] pb</strong> — indistinguível de zero.</p>
<p>O índice também <strong>não reduz o desacordo</strong> do mercado: não há efeito significativo sobre a dispersão nem sobre a entropia das respostas do QPC. A comunicação sinaliza a <em>direção</em> da política sem estreitar o consenso — e sem gerar choque monetário autônomo.</p>
</div>
</div>
</section>
<section id="dinâmica-multivariada-exploratória" class="level3">
<h3 class="anchored" data-anchor-id="dinâmica-multivariada-exploratória">2.6 Dinâmica multivariada (exploratória)</h3>
<p>VAR na frequência das reuniões (ordenação recursiva com sentimento por último, 1 defasagem por AIC/BIC/HQIC/FPE, sistema estável, teste de <em>whiteness</em> <span class="math inline">\(p = 0{,}74\)</span>) e VECM em níveis com posto 1 produzem respostas positivas ao choque de sentimento, mas com <strong>intervalos que atravessam zero</strong>. Consistente com a leitura principal: sem evidência de choque autônomo.</p>
<hr>
</section>
</section>
<section id="discussão" class="level2">
<h2 class="anchored" data-anchor-id="discussão">3. Discussão</h2>
<p>Os resultados formam um padrão coerente:</p>
<ol type="1">
<li><strong>Associação contemporânea forte e estável</strong> — sob hiato HP e Kalman, e em praticamente todas as janelas móveis.</li>
<li><strong>Antecedência bruta é ilusória</strong> — desaparece ao controlar a decisão corrente.</li>
<li><strong>A dimensão importa</strong> — o conteúdo antecedente está no <em>balanço de riscos</em>, não na orientação prospectiva.</li>
<li><strong>A expectativa absorve o efeito</strong> — +13,3 pb sobre o consenso do QPC.</li>
<li><strong>Não há previsão da surpresa</strong> — o resíduo é pequeno e impreciso.</li>
<li><strong>Robustez à endogeneidade</strong> — TSLS e GMM não recuperam coeficiente diferente de zero.</li>
<li><strong>Dinâmica multivariada imprecisa</strong> — VAR e VECM com IC atravessando zero.</li>
</ol>
<p>A leitura econômica: a linguagem do Copom <strong>descreve bem a postura contemporânea</strong> e a assimetria de riscos <strong>carrega sinal sobre a próxima decisão</strong> — mas esse sinal <strong>já está incorporado às expectativas do mercado</strong> antes de a decisão acontecer. É sinalização compartilhada, não informação privada revelada.</p>
<hr>
</section>
<section id="limitações" class="level2">
<h2 class="anchored" data-anchor-id="limitações">Limitações</h2>
<ul>
<li>O <em>score</em> contemporâneo vem de ata publicada <strong>depois</strong> da decisão — associação explicativa, não causalidade.</li>
<li>A amostra tem <strong>48 reuniões</strong> e atravessa regimes de política monetária muito distintos.</li>
<li>Hiato e sentimento parecem estacionários; os testes para desvio da inflação e ΔSelic são inconclusivos.</li>
<li>O <strong>VECM</strong> mistura variáveis com ordens de integração possivelmente diferentes e tem posto de cointegração instável — por isso é apresentado como exploratório.</li>
<li>Janelas móveis sobrepostas geram coeficientes serialmente dependentes.</li>
<li>O filtro HP sofre <strong>viés de ponta</strong> (<em>end-point bias</em>); daí o hiato alternativo por Kalman.</li>
<li>A validação usa <strong>dois agentes independentes</strong>, não avaliadores humanos especialistas — replicação externa permanece desejável.</li>
</ul>
<hr>
</section>
<section id="estrutura-do-projeto" class="level2">
<h2 class="anchored" data-anchor-id="estrutura-do-projeto">Estrutura do Projeto</h2>
<pre><code>Taylor_Sentimento/
│
├── taylor_sentimento_IA_base.qmd    # paper técnico reprodutível
├── NOVA_ABORDAGEM.md                # desenho do índice prospectivo
├── referencias.bib · AM.png
│
├── scripts/
│   ├── 01_build_base.py             # base na frequência de reunião
│   ├── 02_estima_referencia.py      # M0 / M1, OLS + HAC, parâmetros estruturais
│   ├── 03_estima_m2.py              # antecedente (referência e dinâmica)
│   ├── 04_robustez_iv_gmm_m2.py     # TSLS e GMM em dois passos
│   ├── 05_reestima_hiato_kalman.py  # hiato por modelo estrutural
│   ├── 06_var_irf_sentimento.py     # VAR + IRFs
│   ├── 07_vecm_irf_sentimento.py    # VECM exploratório
│   ├── 08_rolling_sentimento.py     # regressões móveis
│   ├── 09_prepare_forward_texts.py  # corpus A+B integral (sem LLM)
│   ├── 10–13_*.py                   # escoragem prospectiva, reestimação, validação
│   └── 14–17_*.py                   # QPC: coleta, surpresa, estimação
│
├── data/
│   ├── base_taylor.csv              # 48 reuniões
│   ├── raw/                         # caches de API + corpus + QPC (42 edições)
│   ├── pilot/                       # piloto, schema e dupla codificação
│   └── results/                     # CSVs de coeficientes e diagnósticos
│
├── figures/                         # IRFs e rolling
├── CHANGELOG.md · versions/
└── portfolio/                       # ESTA ficha + capa</code></pre>
<hr>
</section>
<section id="tecnologias" class="level2">
<h2 class="anchored" data-anchor-id="tecnologias">Tecnologias</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Camada</th>
<th>Tecnologia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Renderização</strong></td>
<td>Quarto + LaTeX (xelatex)</td>
</tr>
<tr class="even">
<td><strong>Pacotes LaTeX</strong></td>
<td><code>booktabs</code>, <code>threeparttable</code> (padrão JEL/AER)</td>
</tr>
<tr class="odd">
<td><strong>Linguagem</strong></td>
<td>Python 3.11+</td>
</tr>
<tr class="even">
<td><strong>Inferência estatística</strong></td>
<td><code>statsmodels</code> (OLS, HAC/Newey-West, HP, Kalman/<code>UnobservedComponents</code>, VAR, VECM, GMM)</td>
</tr>
<tr class="odd">
<td><strong>Manipulação de dados</strong></td>
<td><code>pandas</code>, <code>numpy</code></td>
</tr>
<tr class="even">
<td><strong>Coleta de dados</strong></td>
<td><code>python-bcb</code> (SGS, Focus), <code>requests</code>, <code>openpyxl</code> (QPC)</td>
</tr>
<tr class="odd">
<td><strong>Escoragem por LLM</strong></td>
<td>LangChain + Pydantic (Claude, Gemini, OpenAI) sob <em>schema</em> estruturado</td>
</tr>
<tr class="even">
<td><strong>Visualização</strong></td>
<td><code>plotnine</code></td>
</tr>
<tr class="odd">
<td><strong>Índice de sentimento</strong></td>
<td>Reconstruído a partir do corpus integral; base legada herdada do <a href="sentimento-copom.html">Sentimento COPOM</a></td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="como-executar-localmente" class="level2">
<h2 class="anchored" data-anchor-id="como-executar-localmente">Como Executar Localmente</h2>
<section id="pré-requisitos" class="level3">
<h3 class="anchored" data-anchor-id="pré-requisitos">Pré-requisitos</h3>
<ul>
<li>Python 3.11+ · Quarto ≥ 1.4 · TinyTeX / TeX Live (xelatex)</li>
<li>Chaves de API (Anthropic, Google, OpenAI) <strong>apenas</strong> para reescorar as atas; o fluxo de estimação usa os <em>scores</em> já persistidos.</li>
</ul>
</section>
<section id="instalação" class="level3">
<h3 class="anchored" data-anchor-id="instalação">Instalação</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> <span class="at">-m</span> venv .venv</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">source</span> .venv/bin/activate</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install <span class="at">-r</span> requirements.txt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="pipeline" class="level3">
<h3 class="anchored" data-anchor-id="pipeline">Pipeline</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1) Base na frequência de reunião</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> scripts/01_build_base.py</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2) Estimações de referência e robustez</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> scripts/02_estima_referencia.py</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> scripts/03_estima_m2.py</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> scripts/04_robustez_iv_gmm_m2.py</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> scripts/05_reestima_hiato_kalman.py</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 3) Dinâmica e estabilidade</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> scripts/06_var_irf_sentimento.py</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> scripts/07_vecm_irf_sentimento.py</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> scripts/08_rolling_sentimento.py</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co"># 4) Índice prospectivo (corpus integral)</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> scripts/09_prepare_forward_texts.py</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> scripts/12_reestimate_forward_index.py</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="co"># 5) Surpresa monetária via QPC</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> scripts/15_build_qpc_surprise.py</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> scripts/16_estimate_qpc_surprise.py</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> scripts/17_estimate_qpc_expectation.py</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a><span class="co"># 6) Paper</span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="ex">quarto</span> render taylor_sentimento_IA_base.qmd <span class="at">--to</span> pdf</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
</section>
</section>
<section id="próximos-passos" class="level2">
<h2 class="anchored" data-anchor-id="próximos-passos">Próximos Passos</h2>
<ol type="1">
<li><strong>Preços intradiários de DI</strong> — separar a surpresa da <em>decisão</em> da surpresa de <em>comunicação</em> em janelas estreitas ao redor da publicação da ata. É a extensão prioritária: sem ela, o teste de surpresa depende do QPC, que é pré-reunião mas não intradiário.</li>
<li><strong>Projeção local</strong> — estimar a resposta dinâmica por <em>local projections</em>, mais parcimoniosas que VAR/VECM com <span class="math inline">\(n = 48\)</span>.</li>
<li><strong>Validação com especialistas humanos</strong> — replicar a dupla codificação cega com avaliadores externos.</li>
<li><strong>Sentimento ortogonalizado</strong> — usar o resíduo do tom (controlando expectativas Focus) para isolar a surpresa de comunicação.</li>
<li><strong>Hiato oficial da IFI</strong> — robustez adicional contra HP e Kalman.</li>
<li><strong>Edição do leitor</strong> — <code>taylor_sentimento_IA_publico.qmd</code> (<code>echo: false</code>).</li>
</ol>
<hr>
</section>
<section id="referências" class="level2">
<h2 class="anchored" data-anchor-id="referências">Referências</h2>
<ul>
<li>Clarida, R.; Galí, J.; Gertler, M. (2000). <em>Monetary Policy Rules and Macroeconomic Stability: Evidence and Some Theory</em>. <em>Quarterly Journal of Economics</em>, 115(1), 147–180.</li>
<li>Blinder, A. S.; Ehrmann, M.; Fratzscher, M.; De Haan, J.; Jansen, D.-J. (2008). <em>Central Bank Communication and Monetary Policy</em>. <em>Journal of Economic Literature</em>, 46(4), 910–945.</li>
<li>Hansen, S.; McMahon, M.; Prat, A. (2018). <em>Transparency and Deliberation Within the FOMC: A Computational Linguistics Approach</em>. <em>Quarterly Journal of Economics</em>, 133(2), 801–870.</li>
<li>Hodrick, R. J.; Prescott, E. C. (1997). <em>Postwar U.S. Business Cycles: An Empirical Investigation</em>. <em>Journal of Money, Credit and Banking</em>, 29(1), 1–16.</li>
<li>Johansen, S. (1991). <em>Estimation and Hypothesis Testing of Cointegration Vectors in Gaussian Vector Autoregressive Models</em>. <em>Econometrica</em>, 59(6), 1551–1580.</li>
<li>Newey, W. K.; West, K. D. (1987). <em>A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix</em>. <em>Econometrica</em>, 55(3), 703–708.</li>
<li>Sims, C. A. (1980). <em>Macroeconomics and Reality</em>. <em>Econometrica</em>, 48(1), 1–48.</li>
<li>Taylor, J. B. (1993). <em>Discretion versus Policy Rules in Practice</em>. <em>Carnegie-Rochester Conference Series on Public Policy</em>, 39, 195–214.</li>
<li>Woodford, M. (2003). <em>Interest and Prices: Foundations of a Theory of Monetary Policy</em>. Princeton University Press.</li>
<li>Wirth, R.; Hipp, J. (2000). <em>CRISP-DM: Towards a Standard Process Model for Data Mining</em>.</li>
</ul>
<blockquote class="blockquote">
<p><strong>Projeto-mãe:</strong> <a href="sentimento-copom.html">Sentimento COPOM — Índice de Tom das Atas do Copom com Múltiplos LLMs</a></p>
</blockquote>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/vitorwilher\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Vítor Wilher · <a href="mailto:vitorwilher@analisemacro.com.br">vitorwilher@analisemacro.com.br</a></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>